# Generated by Django 3.0.4 on 2020-07-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0002_auto_20200713_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimentador', models.CharField(default='', max_length=64)),
                ('clave', models.CharField(default='', max_length=64)),
                ('nombre', models.CharField(default='', max_length=64)),
                ('url', models.CharField(default='', max_length=64)),
                ('puntuacion', models.IntegerField(default=0)),
                ('seleccionado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64)),
                ('enlace', models.CharField(default='yo ', max_length=64)),
                ('itemId', models.CharField(default='', max_length=64)),
                ('fotoItem', models.CharField(default='', max_length=64)),
                ('descripcion', models.TextField(default='')),
                ('votosPositivos', models.IntegerField(default=0)),
                ('votosNegativos', models.IntegerField(default=0)),
                ('votosTotales', models.IntegerField(default=0)),
                ('alimentador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miscosasAPP.Alimentador')),
            ],
        ),
    ]
