# Generated by Django 3.0.4 on 2020-07-15 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0003_alimentador_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(default='', null=True, upload_to='Comments')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscosasAPP.Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscosasAPP.Database_Users')),
            ],
        ),
    ]
