# Generated by Django 3.0.4 on 2020-07-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscosasAPP.Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscosasAPP.Database_Users')),
            ],
        ),
    ]
