# Generated by Django 3.0.4 on 2020-07-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0005_voto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='clave',
        ),
    ]
