# Generated by Django 3.0.4 on 2020-07-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0006_auto_20200719_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fotoItem',
            new_name='media',
        ),
    ]
