# Generated by Django 3.0.4 on 2020-07-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0007_auto_20200719_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descripcion',
            new_name='info',
        ),
    ]
