# Generated by Django 3.0.4 on 2020-07-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0008_auto_20200719_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='votosNegativos',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='votosPositivos',
            new_name='likes',
        ),
    ]
