# Generated by Django 3.0.4 on 2020-07-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0009_auto_20200719_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='votosTotales',
            new_name='popularidad',
        ),
        migrations.AlterField(
            model_name='item',
            name='enlace',
            field=models.CharField(default='', max_length=64),
        ),
    ]
