# Generated by Django 3.0.4 on 2020-07-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0010_auto_20200719_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='imagen',
        ),
    ]
