# Generated by Django 3.0.4 on 2020-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0011_remove_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_users',
            name='image',
            field=models.ImageField(default="{%static 'miscosasAPP/avatar.png'%}", null=True, upload_to=''),
        ),
    ]
