# Generated by Django 3.0.4 on 2020-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosasAPP', '0017_auto_20200719_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_users',
            name='image',
            field=models.ImageField(blank=True, default='miscosasAPP/avatar.png', null=True, upload_to='Usuario'),
        ),
    ]
